# Generated by Django 5.2.4 on 2025-07-25 07:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_access"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
