# Generated by Django 5.2.4 on 2025-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_lessons"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="can_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lessons",
            name="status",
            field=models.CharField(
                choices=[
                    ("pub", "Published"),
                    ("draft", "Draft"),
                    ("soon", "Coming Soon"),
                ],
                default="pub",
                max_length=10,
            ),
        ),
    ]
