# Generated by Django 5.2.4 on 2025-07-25 13:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_lessons_can_preview_lessons_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="lessons",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
    ]
