# Generated by Django 5.2.4 on 2025-07-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_lessons_thumbnail_lessons_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessons",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="lessons",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
