# Generated by Django 5.2.4 on 2025-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_lessons_options_lessons_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
