# Generated by Django 5.2.4 on 2025-07-25 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_lessons_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessons",
            options={"ordering": ["order", "-updated"]},
        ),
        migrations.AddField(
            model_name="course",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lessons",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
