# Generated by Django 5.2.4 on 2025-07-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_lessons_options_course_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="public_id",
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
