# Generated by Django 5.2.4 on 2025-07-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_course_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="public_id",
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
