# Generated by Django 5.2.4 on 2025-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_lessons_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("pub", "Published"),
                    ("draft", "Draft"),
                    ("soon", "Coming Soon"),
                ],
                default="pub",
                max_length=10,
            ),
        ),
    ]
