# Generated by Django 5.2.4 on 2025-07-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_alter_course_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("publish", "Published"),
                    ("draft", "Draft"),
                    ("soon", "Coming Soon"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="status",
            field=models.CharField(
                choices=[
                    ("publish", "Published"),
                    ("draft", "Draft"),
                    ("soon", "Coming Soon"),
                ],
                default="publish",
                max_length=10,
            ),
        ),
    ]
