# Generated by Django 5.2.4 on 2025-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_course_status_alter_lessons_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=130, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=130, null=True
            ),
        ),
    ]
