# Generated by Django 5.2.4 on 2025-07-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
