# Generated by Django 5.2.4 on 2025-08-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_email_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverficationevent",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
