# Generated by Django 5.2.4 on 2025-08-02 11:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_alter_emailverficationevent_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverficationevent",
            name="token",
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
